### ISSUE TITLE
ID

### ISSUE THREAD

**Issue by jszachew** [szywo/morele-tracker#1]
Hi, could You say how write grep-sed to get product ID? I've tried something like this: 
`ID= `cat $FILE | grep 'page-product"' | sed 's/^.*data-product-id="\([0-9]*\)"*/\1/'``
but seems not work as I want

**Comment by szywo** [comment]
hey, sorry for not responding, I've already got what I was tracking ;) and script is not used anymore on regular basis (just occasionally)

There are three problems with your `sed` expression:

1.  your number group will contain only one character because asterisk `*` is placed after quotation mark and it should be right after square bracket: `[0-9]*`
2. `sed` needs to have escaped parentheses `()` so your number group `([0-9]*)` should look like this ```\([0-9]*\)```
3. `grep` returns whole line and if you want to start looking for pattern from its first position and you don't know at which position `data-product-id` string begins instead one any-character `.` at first position you should use many any-characters `.*` at the start of a string: `s/^.*data-product-id`

Then there is a `grep` problem as it returns two exactly the same lines. I think it would be manageable but I also found another distinct line containing required data: `<div class="product-data apri-data" data-product-id="`

Complete line would go:
```ID=`cat $FILE | grep "<div class=\"product-data apri-data\" data-product-id=\"" | sed 's/^.*\sdata-product-id="\([\0-9]*\)"\s.*$/\1/'\` ```

Hope it will be of some help.
